### PR TITLE
Arrow plotting hook

### PR DESCRIPTION
**Pull request by jlstevens**
The first PR contributing a notebook!

This is an example of a plotting hook, inspired by the discussion on ioam/holoviews#34.

As planned, anyone submitting a PR will be given a link to the contribution guidelines.

The only thing I'm not entirely sure about yet is whether plotting hooks will be a general enough category to be worth its own subdirectory. For now there is a single file so we can come back to this issue later.

### CODE REVIEW

**Comment by jlstevens** [comment]
@jbednar @philippjfr 

Should we have a policy to always 'squash and merge' for notebooks containing output? If so, this should be mentioning in the contribution guidelines. I think this policy could help avoid bloating the repo...

**Comment by philippjfr** [comment]
Sounds good, can you set that up to be automatic?

**Comment by jlstevens** [comment]
Done! This means all merges in this repo will be 'Squash and merge'.

**Comment by jbednar** [comment]
Looks good, and happy to see it merged.  It might be good if the notebook mentioned at the end that this is not the only way the same goal could have been achieved.  E.g. what if people *often* needed to use slanted arrows in arbitrary directions?  Presumably this approach would be a pain in the long run, so it would be good to explain how one could e.g. subclass Arrow to create a new Element with this functionality.

**Comment by philippjfr** [comment]
We do have an Arrow Element, which currently is too limited. There's even an issue to improve it: https://github.com/ioam/holoviews/issues/34

**Comment by jbednar** [comment]
Sure, but I mean point them to some aspect of the documentation which explains the process of adding a new Element type if they don't want to wait for us to improve Arrow.

**Comment by philippjfr** [comment]
Yes, absolutely, is this repo the best place to gather that information? We definitely need a developer docs section on the website.

**Comment by jbednar** [comment]
I wouldn't expect to see full holoviews documentation on this site, just links back to the real documentation (or to other examples on this site).

**Comment by jlstevens** [comment]
Ok, I added a paragraph with the recommended (long-term) approach. I wouldn't subclass ``Arrow``: I would extend it with an ``angle`` and a ``length`` parameter.

I don't think it would be too hard to implement (including bokeh support) but this enhancement isn't a priority right now. As I state in the notebook, PRs are welcome!

Ready to review/merge.

**Comment by jbednar** [comment]
Looks good.  Just to be totally clear, I know *you* wouldn't subclass Arrow, but since this is a user-focused site, I was looking for suggestions about what a *user* would do.  A user could certainly do what you suggest there, and then either maintain a private fork or submit a PR.  But what if a user wants to have functionality like this and maintain it over time without putting it in HoloViews?  That's a big category of use cases, I would think. Would you suggest that they copy the corresponding code that you mentioned and make the edits locally?  Or subclass Arrow?  Or...?

**Comment by jlstevens** [comment]
In this case, the extra parameters are things that ought to be in the ``Arrow`` implementation we supply (i.e when we get round to implementing it). For this reason, it would be wasteful for the user to maintain their own version when we would be very happy to accept a PR adding these features.

In *general*, if there is something very user specific then yes, I would recommend that the user subclasses whichever element is closest to what the way and add the corresponding plotting class. This would be something I would like an example of in ``holoviews-contrib`` but probably not in this specific notebook.

**Comment by jbednar** [comment]
That's what I thought.  Is it ok if I edit this notebook to say what you just did, or would you rather add that yourself?

**Comment by jlstevens** [comment]
> Is it ok if I edit this notebook to say what you just did

Sure! This repo is all about collaboration. :-)

**Comment by jbednar** [comment]
Actually, I don't quite have the information I need.  I think there should be a final sentence saying something like:

    "On the other hand, if you wanted to add functionality to a HoloViews element that was not suitable for becoming part of the public HoloViews distribution, you could follow similar steps, but by subclassing that element and its plotting class instead and maintaining those subclasses in your own code.\n"

I assume there's a registry that connects the element with its plotting class that also needs to be mentioned?

**Comment by jlstevens** [comment]
Sounds like it would be best to discuss this in a different example notebook. I agree it is material that should be covered but in the end, I don't think this is the best place for it.

**Comment by jbednar** [comment]
That would be fine, with a link from here.  But if that doesn't exist, then it should at least be here...

**Comment by philippjfr** [comment]
I think we can merge as is. I'll try to add an example of adding a pie chart element in another PR.

**Pull request merged**
